### ISSUE TITLE
auto_prune option has no effect

### ISSUE THREAD

**Issue by zmanji** [nanoc/nanoc#122]
I read somewhere that if I set:

``` YAML
prune:
    auto_prune: true
```

in my config.yaml then the compile command would run prune before compilation. I have done this and `nanoc compile` does not prune stray files. My config in full:

``` YAML

# A list of file extensions that nanoc will consider to be textual rather than
# binary. If an item with an extension not in this list is found,  the file
# will be considered as binary.
text_extensions: ['coffee', 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'pandoc', 'php', 'rb', 'sass', 'scss', 'tex', 'txt', 'xhtml', 'xml' ]

# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
output_dir: output

# A list of index filenames, i.e. names of files that will be served by a web
# server when a directory is requested. Usually, index files are named
# “index.hml”, but depending on the web server, this may be something else,
# such as “default.htm”. This list is used by nanoc to generate pretty URLs.
index_filenames: [ 'index.html' ]

# Whether or not to generate a diff of the compiled content when compiling a
# site. The diff will contain the differences between the compiled content
# before and after the last site compilation.
enable_output_diff: false

# The data sources where nanoc loads its data from. This is an array of
# hashes; each array element represents a single data source. By default,
# there is only a single data source that reads data from the “content/” and
# “layout/” directories in the site directory.
data_sources:
  -
    # The type is the identifier of the data source. By default, this will be
    # `filesystem_unified`.
    type: filesystem_unified

    # The path where items should be mounted (comparable to mount points in
    # Unix-like systems). This is “/” by default, meaning that items will have
    # “/” prefixed to their identifiers. If the items root were “/en/”
    # instead, an item at content/about.html would have an identifier of
    # “/en/about/” instead of just “/about/”.
    items_root: /

    # The path where layouts should be mounted. The layouts root behaves the
    # same as the items root, but applies to layouts rather than items.
    layouts_root: /

    config:
      allow_periods_in_identifiers: true

# Configuration for the “watch” command, which watches a site for changes and
# recompiles if necessary.
watcher:
  # A list of directories to watch for changes. When editing this, make sure
  # that the “output/” and “tmp/” directories are _not_ included in this list,
  # because recompiling the site will cause these directories to change, which
  # will cause the site to be recompiled, which will cause these directories
  # to change, which will cause the site to be recompiled again, and so on.
  dirs_to_watch: [ 'content', 'layouts', 'lib' ]

  # A list of single files to watch for changes. As mentioned above, don’t put
  # any files from the “output/” or “tmp/” directories in here.
  files_to_watch: [ 'config.yaml', 'Rules', 'compass_config.rb']

  # When to send notifications (using Growl or notify-send).
  notify_on_compilation_success: false
  notify_on_compilation_failure: true

# Required for XML Sitemap
base_url: http://www.zameermanji.com

prune:
  # This mens nanoc will automatically run nanoc prune every time I compile
  # note that it is sort of dangerous
  auto_prune: true

deploy:
  default:
    kind: rsync
    dst: "zameermanji.com:~/public_html"
    options: ['-avze ssh', '--delete-after']
```
