### ISSUE TITLE
YAML layouts not processed

### ISSUE THREAD

**Issue by HaoZeke** [nanoc/nanoc#1246]
Metadata for other commands are not acceptable for layouts.

### Steps to reproduce

1. Write a yaml config file like so:

```yaml
---
author:
- Rohit Goswami
fontsize: 12pt
date: 2017-11-5
subject: "someTesst"
tags: [Markdown, Example]
# Citations
bibliography: "src/refs.bib"
...


<%= yield %>
```
2.  Attempt to use filter.

### Expected behavior

The file generated is expected to be one made according to frontmatter + document yield.

### Actual behavior

The following error:

```bash
Nanoc::DataSources::Filesystem::Errors::InvalidFormat: The file 'layouts/slideConf.yml.erb' appears to start with a metadata section (three or five dashes at the top) but it does not seem to be in the correct format.
```

### Details

Is there a way to prevent nanoc from reading metadata from layout files?
