### ISSUE TITLE
Nanoc environments logic happens before parent config files logic

### ISSUE THREAD

**Issue by gpakosz** [nanoc/nanoc#1351]
If I understood correctly, top level settings from a configuration file that references a parent configuration file should override the default environment defined in said parent file.

`parent.yaml`:
```
environments:
  default:
    foo: 'bar'
```

`nanoc.yaml`:
```
foo: 'baz'
parent_config_file: 'parent.yaml'
```

### Steps to reproduce

1. `nanoc create site`
2. `cd site`
2. `printf "environments:\n  default:\n    foo: 'bar'" > parent.yaml`
3. `printf "foo: 'baz'\nparent_config_file: 'parent.yaml'" > nanoc.yaml`
4. `printf "preprocess { puts @config[:foo] }" >> Rules`
5. `nanoc compile`

### Expected behavior

You should see `baz` in the output, but it prints `bar`.

### Details

I tested with Nanoc version `4.8.19`.

As far as I remember, `environments` landed after `parent_config_file` but `parent_config_file` wasn't documented.

The workaround is to place the `foo: 'baz` override inside a default environment:

`nanoc.yaml`:
```
environments:
  default:
    foo: 'baz'
parent_config_file: 'parent.yaml'
```

**Comment by ddfreyne** [comment]
Oh yeah, that’s counterintuitive!

**Comment by ddfreyne** [comment]
Hmm, on second though, I’m not sure whether this is unexpected behavior. In any case, at least worth documenting.

My personal opinion is that the most _specific_ definition in an environment should win. So, given the following:

```
environments:
  default:
    foo: 'aaa'
```

```
foo: 'bbb'
```

… then I’d expect `foo` to be `aaa` when the environment is `default`, and `bbb` if not, _regardless_ of where it is defined (the config file, a parent config file, a parent’s parent config file, …).

* * *

In your example, you have

`parent.yaml`:

```yaml
environments:
  default:
    foo: 'bar'
```

`nanoc.yaml`:

```yaml
foo: 'baz'
parent_config_file: 'parent.yaml'
```

… which Nanoc turns into a single config file (in memory):

```yaml
environments:
  default:
    foo: 'bar'
foo: 'baz'
```

If the environment is `default`, the value of `foo` will indeed be `bar` (not `baz`).

@gpakosz I’d like to keep the current behavior, but document it on the web site. What do you think?

**Comment by gpakosz** [comment]
Documenting this exact example and highlighting the specificity rule sounds good. It will help people decide what's a *regular* configuration setting and what's *environment specific* configuration setting. And maybe what's an *environment specific override*. And in that respect I believe the doc is a bit misleading

> The default environment is, as the name suggests, the environment that will be used when no environment is explicitly specified. The example above is thus equivalent to the following:
> ```
> environments:
>   default:
>     base_url: http://nanoc.dev
>   prod:
>     base_url: http://nanoc.ws
> ```

Not exactly. You end up with the same result but it's not equivalent in terms of what's happening.
When you do
```
base_url: http://nanoc.dev

environments:
  prod:
    base_url: http://nanoc.ws
```
Then the `prod` environment **overrides** the **regular** `base_url` configuration setting.

But when you do
```
environments:
  default:
    base_url: http://nanoc.dev
  prod:
    base_url: http://nanoc.ws
```
Then there's no **overriding** going on. You have **environment specific** configuration settings that share a same name. And would I define a third environment named `staging`
```
environments:
  staging:
    minify: false
```
Then when compiling with `--env=staging`, `base_url` simply doesn't exist.
