### ISSUE TITLE
nanoc-live does not use lib_dir

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1556]
### Steps to reproduce

1. Change lib_dir in configuration
2. Run nanoc-live

### Expected behavior

nanoc-live looks at the lib dir specified in lib_dir

### Actual behavior

nanoc-live uses `lib/`, and ignores the configuration

### Details

nanoc-live should not hardcode `lib`.

Also, if there is no lib dir, nanoc-live should still function properly.

### Crash log

n/a

**Comment by gpakosz** [comment]
I'm facing the issue with the following configuration:

```
.
├── _factory
│   ├── content
│   │   └── ...
│   ├── layouts
│   │   └── ...
│   ├── lib
│   │   └── ...
│   └── nanoc.yaml
├── content
│   └── ...
└── nanoc.yaml
```

The top level `nanoc.yaml` file uses `parent_config_file: _factory/nanoc.yaml`.
The `_factory/nanoc.yaml` file contains:
```
...
lib_dirs:
  - _factory/lib
  - lib
output_dir: output
...
data_sources:
  - type: filesystem
    identifier_type: full
    encoding: utf-8
    items_root: /
    layouts_root: /
  - type: filesystem
    identifier_type: full
    encoding: utf-8
    items_root: /
    content_dir: static
    layouts_dir: null
    layouts_root: null
  - type: filesystem
    identifier_type: full
    encoding: utf-8
    content_dir: _factory/content
    items_root: /_factory
    layouts_dir: _factory/layouts
    layouts_root: /_factory
  - type: filesystem
    identifier_type: full
    encoding: utf-8
    items_root: /_factory
    content_dir: _factory/static
    layouts_dir: null
    layouts_root: null
...
```

While the top level `content/` directory will always exist, the top level `layouts/` and `lib/` directories might not.

With this setup, I expect `nanoc-live` to watch
- `content/`
- `layouts/` when it exists
- `lib/`when it exists
- `_factory/content/`
- `_factory/layouts/`
- `_factory/lib/`

For the record, here's my current `Guardfile` setup
- `Guardfile`
   ```
   ::Guard::Guardfile::Evaluator.new(:guardfile => File.join(File.dirname(__FILE__), '_factory/Guardfile')).evaluate
   ```
- `_factory/Guardfile`
   ```
   guard 'nanoc' do
     watch('nanoc.yaml')
     watch('Rules')
     watch(%r{^(content|layouts|lib)/.*$})

     watch('_factory/nanoc.yaml')
     watch('_factory/Rules')
     watch(%r{^_factory/(content|layouts|lib)/.*$})
   end

   guard 'livereload' do
     watch(%r{output/.*$})
   end
   ```
