### ISSUE TITLE
Enhancement: Canonical link tag to main domain

### ISSUE THREAD

**Issue by redfast00** [nanoc/nanoc#1642]
At Zeus WPI (:wave: @denisdefreyne), we run our site on multiple domains: both on zeus.ugent.be and zeus.gent. We also have <number>.pr.zeus.gent, which deploys previews of pull requests against the site repository. When searching content on for example Google, both zeus.gent and zeus.ugent.be show up, diluting search results. A (standardized) way to prevent duplicate content is [the canonical link element](https://en.wikipedia.org/wiki/Canonical_link_element).

The base domain/path could be an option in the nanoc.yml config file, which would then be used on each page to append the "page path" to.

What do you think about this?

**Comment by opatry** [comment]
I do kind of the same thing and went for:

- environments for local dev vs remote
```yml
environments:
  default:
    site:
      url: 'http://localhost'
  prod:
    site:
      url: 'https://prod.com'
```

Then I use it as follow `@config[:site][:url]`.
