### ISSUE TITLE
Allow us to exclude folder/files from automatic evaluation and inclusion.

### ISSUE THREAD

**Issue by envygeeks** [nanoc/nanoc#313]
It would be nice so we can control load and situations, such as when I am testing my helpers I don't need all the other inclusions.  Right now I have to override certain functions inside of Nanoc to achieve this but it would be nice if we could do this automatically with `nanoc.yaml`.

Better explanation:

``` yaml
autoload:
  exclude: "*"
  include:
    - "helpers.rb"
    - "autoload/.+\.rb"
```
- `exclude: *` invokes explicit with whitelist.
- `exclude: []` invokes implicit with blacklist.

This would allow maximum flexibility with minimum impact.
