### ISSUE TITLE
Using slim filter displays raw HTML in content

### ISSUE THREAD

**Issue by jwoertink** [nanoc/nanoc#324]
The site compiles fine using slim as the default layout, but setting the content pages to slim only prints out the raw html. Here are the steps I took to reproduce
- gem install nanoc
- gem install adsf
- gem install slim
- nanoc create-site sample
- rename `layouts/default.html` to `layouts/default.slim`
- rename `content/index.html` to `content/index.slim`
- slim up both files
- add :slim in the `Rules` file
- compile and view
  ![screen shot 2013-07-24 at 11 04 18 am](https://f.cloud.github.com/assets/2391/850545/7da4674e-f48b-11e2-9f75-fa8362a484fb.png)

Rules file

``` ruby
#!/usr/bin/env ruby
compile('/stylesheet/') { }
compile '*' do
  unless item.binary?
    filter :slim
    layout 'default'
  end
end
route('/stylesheet/') { '/style.css' }
route '*' do
  if item.binary?
    item.identifier.chop + '.' + item[:extension]
  else
    item.identifier + 'index.html'
  end
end
layout '*', :slim
```

nanoc.yml

``` yml
text_extensions: [ 'slim', 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.slim' ]
enable_output_diff: false
prune:
  auto_prune: false
  exclude: [ '.git', '.hg', '.svn', 'CVS' ]
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
    allow_periods_in_identifiers: false
watcher:
  dirs_to_watch: [ 'content', 'layouts', 'lib' ]
  files_to_watch: [ 'nanoc.yaml', 'Rules' ]
  notify_on_compilation_success: true
  notify_on_compilation_failure: true
```

layouts/default.slim

``` slim
doctype html
html
  body
    #main
      h1 renders properly
      = yield
```

content/index.slim

``` slim
h1 renders raw html here
p and here.
```
