### ISSUE TITLE
Deploy Credentials in Nanoc.yaml File

### ISSUE THREAD

**Issue by tmus** [nanoc/nanoc#539]
Forgive me if this is in the documentation somewhere.

I've set a key in `nanoc.yaml` like so

```yaml
deploy:
  default:
    kind:                  fog
    provider:              aws
    region:                eu-west-1
    bucket:                name
    aws_access_key_id:     
    aws_secret_access_key:
    path_style:            true
```

Obviously adding the aws credentials to this wouldn't be wise.

Is there a way to reference an external file, maybe `environment.yaml` or something, from `nanoc.yaml` so that I can add it to `.gitignore` and keep it out of VCS? Maybe this is in development? Or is it simply not possible? From what I've seen online, `yaml` doesn't include an `include` directive.
