### ISSUE TITLE
How to use environments?

### ISSUE THREAD

**Issue by lifepillar** [nanoc/nanoc#994]
I haven't followed the development of the environments feature, but I see that it is now stable,  although there is no documentation yet. I have naïvely tried to move some variables under an environment:

```
environment:
  default: &default
    site:
      name: My Site
      author: Me
    ...
```
but then compilation fails. Maybe, is it possible to get a quickstart?
